function getQuote(num) {
    const quoteList = [
        "If food were free, why work?",
        "Your diet is a bank account. Good food choices are good investments.",
        "Food is for eating, and good food is to be enjoyed… I think food is, actually, very beautiful in itself.",
        "I get way too much happiness from good food.",
        "If you combine good flavors, food turns into an orchestra.",
        "Food is really and truly the most effective medicine.",
        "You know, food is such – it’s a hug for people.",
        "The closest I’ve been to a diet this year is erasing food searches from my browser history.",
        "My friends tell me that cooking is easy, but it’s not easier than not cooking.",
        "There’s nothing more romantic than Italian food.",
        "Every time you use the word ‘healthy,’ you lose. The key is to make yummy, delicious food that happens to be healthy.",
        "I’m just someone who likes cooking and for whom sharing food is a form of expression.",
        "I think about food literally all day every day. It’s a thing.",
        "I think I was immediately fed, so food became a very important part of my life.",
        "If I can, I love staying in pajamas all day and watching movies and eating good food.",
        "I was always a junk food person, still am.",
        "I love pizza. I want to marry it, but it would just be to eat her family at the wedding. ",
        "If someone else is paying for it, food just tastes a lot better.",
        "Eating good food is my favorite thing in the whole world. Nothing is more blissful.",
        "Food is fuel",
        "All I want for Christmas is food",
        "I’m soy into you.",
        "Anything is good if it’s made of chocolate.",
        "I like food. I like eating. And I don’t want to deprive myself of good food.",
        "The only thing I like better than talking about food is eating.",
        "Everything you see I owe to spaghetti.",
        "Food is an important part of a balanced diet.",
        "I cook with wine. Sometimes I even add it to the food.",
        "Cauliflower is nothing but cabbage with a college education.",
        "If you’re afraid of butter use cream.",
        "Cooking is like love. It should be entered into with abandon or not at all.",
        "Life is a combination of magic and pasta.",
        "Promises and pie-crust are made to be broken.",
        "Cheese – milk’s leap towards immortality.",
        "I like rice, rice is great if you’re hungry and want 2000 of something.",
        "Always serve too much hot fudge sauce on hot fudge sundaes. It makes people overjoyed and puts them in your debt.",
        "We all eat, & it would be a sad waste of an opportunity to eat badly.",
        "First, we eat then we do everything else.",
        "A balanced diet is a cookie in each hand.",
        "People who love to eat always the best people.",
        "I like hashtags because they look like waffles #",
        "Food is our common ground, a universal experience.",
        "There is no sincere love than the love of food.",
        "Let food be thy medicine and medicine be thy food.",
        "Good food is good mood.",
        "Ways to my heart: 1. Buy me food 2. Make me food 3. Be food",
        "You can’t live a full life on an empty stomach.",
        "Happiness is homemade.",
        "Life is a combination of magic and pasta.",
        "There is no sincere love than the love of food.",
        "A taste of the food life.",
        "There is no sincerer love than the love of food.",
        "Don’t be upsetti, eat some spaghetti.",
        "Donut worry be happy.",
        "You’re my baegal.",
        "Donut kill my vibe.",
        "I’m on a seafood diet. I see food, I eat it.",
        "There’s no we in fries.",
        "Count the memories not the calories."
    ];

    return quoteList[num];
}

module.exports = getQuote;
